first commit
ClevertecFrontendLab/sprint1-forest331 pull request #1
Opened 2023-01-30 19:10 UTC by forest331

2023-01-30 19:13 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/forest331/1675105987/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/forest331/1675105987/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/forest331/1675105987/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/forest331/1675105987/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/forest331/1675105987/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/forest331/1675105987/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/forest331/1675105987/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/forest331/1675105987/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/forest331/1675105987/content-window.png)

2023-01-30 19:28 UTC, klichkovskiy requested changes

2023-01-30 19:28 UTC, klichkovskiy commented on src/index.js
> +        <Route path='/' element={<Layout />}>
шрифт не по макету

2023-01-30 19:28 UTC, klichkovskiy commented on src/pages/main/content/button-nav/button-navigation-list.jsx
> +const pageList = () => console.log('click');
убрать консольку

2023-01-30 19:28 UTC, klichkovskiy commented on src/pages/main/content/button-nav/button-navigation-tile.jsx
> +  console.log('click');
убрать консольку

2023-01-30 19:28 UTC, klichkovskiy commented on src/pages/layout/layout-main-page.jsx
> +      {/* <ContentMainPage /> */}
Убрать закомментированный код

2023-01-30 19:28 UTC, klichkovskiy commented on src/pages/main/content/book-tile/book-tile.module.css
> +/* .images {
Убрать закомментированный код по всему приложению!

2023-01-30 19:28 UTC, klichkovskiy commented on src/pages/main/content/button-nav/button-navigation-tile.jsx
> +export const ButtonNavigationTile = () => (
Это все разные компоненты раздели их по разным папкам

2023-01-30 19:28 UTC, klichkovskiy commented on src/pages/main/content/book/book.jsx
> +export function BookList() {
Убери разные компоненты из одной папки по всему коду

2023-01-30 19:28 UTC, klichkovskiy commented on src/pages/main/content/book/book.jsx
> +      <dir className={classes.book_items}>{booksList}</dir>
может div?

2023-01-30 19:28 UTC, klichkovskiy commented on src/pages/fooret/footer.jsx
> +    <ul className={classes.footer_links}>
можно промапать

2023-01-30 19:28 UTC, klichkovskiy commented on src/pages/main/content/book/book-card.jsx
> +      <div className={classes.rating_result}>
У тебя же этот кусок выше есть (если в двух и более местах встречается можно смело делать компонентом.

2023-01-30 19:28 UTC, klichkovskiy commented on src/pages/main/content/navigation.jsx
> +      <ButtonNavigationList data-test-id='button-menu-view-list' />
Не работает переход на смену вида списком. Посмотри по скринам!

2023-02-01 00:42 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/forest331/1675212161/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/forest331/1675212161/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/forest331/1675212161/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/forest331/1675212161/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/forest331/1675212161/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/forest331/1675212161/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/forest331/1675212161/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/forest331/1675212161/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/forest331/1675212161/content-window.png)

2023-02-01 07:30 UTC, klichkovskiy requested changes

2023-02-01 07:30 UTC, klichkovskiy commented on src/pages/main/content/books-tile/books-tile.jsx
> +export const BookTile = () => {
А чем принципиально это отличается от компонента выше? Зачем делать 2 разных компонента, если они очень похожи

2023-02-01 07:30 UTC, klichkovskiy commented on src/pages/main/content/page-book/information-book/information-book.jsx
> +export const InformationBook = () => (
![image](https://user-images.githubusercontent.com/62481116/215978715-c07d75e3-0332-4a00-b275-50981e98e65c.png)
Поломалось - почини

2023-02-01 07:30 UTC, klichkovskiy commented on src/pages/main/content/books-list/book-list-card.jsx
> +    <button className={props.isBooked === true ? classes.book_button_free : classes.book_button} type='button'>
![image](https://user-images.githubusercontent.com/62481116/215978880-896fe9f3-370b-46db-8ba1-5e37655d396f.png)
Почини

2023-02-01 07:30 UTC, klichkovskiy commented on src/pages/main/content/books-list/book-list-card.jsx
> +        <img className={classes.images} src={Img} alt='' />
![image](https://user-images.githubusercontent.com/62481116/215978986-3ad2854b-fa4f-4d82-812d-fd921573c691.png)
этого значка не должно быть

2023-02-01 20:43 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/forest331/1675284187/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/forest331/1675284187/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/forest331/1675284187/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/forest331/1675284187/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/forest331/1675284187/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/forest331/1675284187/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/forest331/1675284187/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/forest331/1675284187/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/forest331/1675284187/content-window.png)

2023-02-01 20:44 UTC, klichkovskiy approved these changes

2023-02-01 20:51 UTC, merged